api:
  - .github/workflows/ci_cd.yml
  - api/**
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
ingestion_server:
  - .github/workflows/ci_cd.yml
  - ingestion_server/**
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
frontend:
  - .github/workflows/ci_cd.yml
  - frontend/**
  - package.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - .npmrc
  - .pnpmfile.cjs
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
lint:
  - prettier.config.js
  - .prettierignore
  - .eslintrc.js
  - .eslintignore
  - .pre-commit-config.yaml
