# Configuration file for the action `BetaHuhn/repo-file-sync-action`
# Docs: https://github.com/BetaHuhn/repo-file-sync-action
# Workflow: Meta file sync

group:
  # Openverse
  - repos: |
      WordPress/openverse-catalog
      WordPress/openverse-api
      WordPress/openverse-frontend
      WordPress/openverse-browser-extension
      WordPress/openverse-infrastructure
    files:
      # Synced workflows
      - source: .github/workflows/new_issues.yml
        dest: .github/workflows/new_issues.yml
      - source: .github/workflows/new_prs.yml
        dest: .github/workflows/new_prs.yml
      - source: .github/workflows/label_new_pr.yml
        dest: .github/workflows/label_new_pr.yml
      - source: .github/workflows/pr_label_check.yml
        dest: .github/workflows/pr_label_check.yml
      - source: .github/workflows/pr_ping.yml
        dest: .github/workflows/pr_ping.yml
      - source: .github/workflows/actionlint.yml
        dest: .github/workflows/actionlint.yml
      - source: .github/actionlint-matcher.json
        dest: .github/actionlint-matcher.json
      - source: .github/workflows/subscribe_to_label.yml
        dest: .github/workflows/subscribe_to_label.yml
      - source: .github/subscribe-to-label.json
        dest: .github/subscribe-to-label.json
      # Downstream workflows
      - source: .github/workflows_downstream/draft_release.yml
        dest: .github/workflows/draft_release.yml
      - source: .github/release_drafter.yml
        dest: .github/release_drafter.yml
      # Templates
      - source: .github/ISSUE_TEMPLATE/
        dest: .github/ISSUE_TEMPLATE/
      - source: .github/PULL_REQUEST_TEMPLATE.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
