# Configuration file for the action `BetaHuhn/repo-file-sync-action`
# Docs: https://github.com/BetaHuhn/repo-file-sync-action
# Workflow: Meta file sync

group:
  - repos: |
      WordPress/openverse-infrastructure
    files:
      # Dependencies for some workflows
      - source: automations/python/
        dest: automations/python/
      - source: automations/data/
        dest: automations/data/
      - source: automations/js/src/project_automation/
        dest: automations/js/src/project_automation/
      - source: automations/js/src/utils/
        dest: automations/js/src/utils/
      - source: automations/js/src/label_pr.mjs
        dest: automations/js/src/label_pr.mjs
      # Synced workflows
      - source: .github/workflows/issue_automations.yml
        dest: .github/workflows/issue_automations.yml
      - source: .github/workflows/pr_automations.yml
        dest: .github/workflows/pr_automations.yml
      - source: .github/workflows/pr_automations_init.yml
        dest: .github/workflows/pr_automations_init.yml
      - source: .github/workflows/pr_label_check.yml
        dest: .github/workflows/pr_label_check.yml
      - source: .github/workflows/pr_ping.yml
        dest: .github/workflows/pr_ping.yml
      - source: .github/workflows/subscribe_to_label.yml
        dest: .github/workflows/subscribe_to_label.yml
      - source: .github/subscribe-to-label.json
        dest: .github/subscribe-to-label.json
      # Templates
      - source: .github/ISSUE_TEMPLATE/bug_report.md
        dest: .github/ISSUE_TEMPLATE/bug_report.md
      - source: .github/ISSUE_TEMPLATE/config.yml
        dest: .github/ISSUE_TEMPLATE/config.yml
      - source: .github/ISSUE_TEMPLATE/feature_request.md
        dest: .github/ISSUE_TEMPLATE/feature_request.md
