services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
      args:
        - PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}
    volumes:
      - ../node_modules:/node_modules:rw,Z
      - .:/frontend:rw,Z
    user: ${USER_ID}
    working_dir: /frontend
    entrypoint: >
      /bin/sh -c '
      pnpm install;
      pnpm ${TEST_COMMAND} ${PLAYWRIGHT_ARGS:-};
      '
    environment:
      # This makes the webserver that Playwright runs show the build
      - DEBUG=pw:webserver
      - UPDATE_TAPES=${UPDATE_TAPES:-false}
      - FASTSTART=${FASTSTART:-false}
      - PLAYWRIGHT_BASE_URL=${PLAYWRIGHT_BASE_URL:-}
      - HMAC_SIGNING_SECRET=${HMAC_SIGNING_SECRET:-}
