services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
      args:
        - PACKAGE_MANAGER=${PACKAGE_MANAGER}
        - PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}
    volumes:
      - ../node_modules:/node_modules
      - .:/frontend
      - ${PWD}/../tsconfig.base.json:/tsconfig.base.json
    user: ${USER_ID}
    working_dir: /frontend
    command: pnpm ${TEST_COMMAND} ${PLAYWRIGHT_ARGS:-}
    environment:
      # This makes the webserver that Playwright runs show the build
      - DEBUG=pw:webserver
      - UPDATE_TAPES=${UPDATE_TAPES:-false}
      - FASTSTART=${FASTSTART:-false}
