name: openverse/build-docs
description: Build Openverse full-stack docs

runs:
  using: "composite"
  steps:
    - name: Build Sphinx
      shell: bash
      run: |
        just api/sphinx-make
        sudo chown "$USER:$USER" -R ./api
      env:
        DC_USER: root

    - name: Install translations
      shell: bash
      run: |
        just frontend/run i18n

    - name: Build Storybook
      shell: bash
      run: |
        just frontend/run storybook:build

    - name: Build Tailwind Config Viewer
      shell: bash
      run: |
        just frontend/run tcv:build

    # Storybook will be available at `/storybook`
    # Tailwind will be available at `/tailwind`
    - name: Merge all docs
      shell: bash
      run: |
        mv api/build/html /tmp/docs
        mv frontend/storybook-static /tmp/docs/storybook
        mv frontend/.tcv-export /tmp/docs/tailwind
