language: python
python:
- '3.6'
services:
  - docker
install:
  - pip3 install -r ingestion_server/requirements.txt
before_script:
  - cd ingestion_server
script:
  - python3 test/integration_tests.py
