language: python
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-client-10
env:
  - CCCAPI_CONTAINER_NAME=cccatalogapi_web_1
python:
- '3.6'
services:
  - docker
install:
  - pip3 install -r ingestion_server/requirements.txt
  - pip3 install -r cccatalog-api/requirements.txt
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose up -d
  - bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://localhost:8000/healthcheck)" != "200" ]]; do sleep 5; done'
  - ./load_sample_data.sh
  - bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://localhost:8000/image/search?q=test)" != "200" ]]; do sleep 5; done'
script:
  - pycodestyle cccatalog-api/cccatalog --exclude='cccatalog-api/cccatalog/api/migrations' --max-line-length=80 --ignore=E402 
  - pycodestyle ingestion_server/*.py --max-line-length=80 --ignore=E402
  - cd cccatalog-api/test && ./run_test.sh
  - cd ../../ingestion_server && python3 test/integration_tests.py
