language: python
env:
  - DOCKER_COMPOSE_VERSION=1.21.0
python:
- '3.6'
services:
  - docker
install:
  - pip3 install -r ingestion_server/requirements.txt
  - pip3 install -r cccatalog-api/requirements.txt
before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose up -d
  - bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://localhost:8000/healthcheck)" != "200" ]]; do sleep 5; done'
  - ./load_sample_data.sh
script:
  - cd cccatalog-api/test && ./run_test.sh
  - cd ../../ingestion_server && python3 test/integration_tests.py
