language: python
python:
- '3.6'
before_install:
  - cd es_syncer
install:
  - pip install -r requirements.txt
before_script:
  - cd es_syncer
script:
  - python test/integration_tests.py
services:
  - docker

