version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "cccatalog"
      POSTGRES_USER: "deploy"
      POSTGRES_PASSWORD: "deploy"
    healthcheck:
      test: "pg_isready -U deploy -d cccatalog"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cccatalog-api
    ports:
      - "8000:8000"
    depends_on:
      - db
