version: '3'
services:
  db:
    image: postgres:10.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "openledger"
      POSTGRES_USER: "deploy"
      POSTGRES_PASSWORD: "deploy"
      POSTGRES_HOST: "0.0.0.0"
    healthcheck:
      test: "pg_isready -U deploy -d openledger"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
    environment:
      # disable XPack
      # https://www.elastic.co/guide/en/elasticsearch/reference/5.3/docker.html#_security_note
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl -si -XGET 'localhost:9200/_cluster/health?pretty' | grep -qE 'yellow|green'"]
      interval: 10s
      timeout: 60s
      retries: 10
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  web:
    build: ./cccatalog-api/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cccatalog-api:/cccatalog-api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es
    environment:
      DJANGO_DATABASE_NAME: "openledger"
      DJANGO_DATABASE_USER: "deploy"
      DJANGO_DATABASE_PASSWORD: "deploy"
      DJANGO_DATABASE_HOST: "db"
      PYTHONUNBUFFERED: "0"
      DJANGO_DEBUG_ENABLED: "True"
      ELASTICSEARCH_URL: "es"
      ELASTICSEARCH_PORT: "9200"
      DISABLE_GLOBAL_THROTTLING: "True"
    stdin_open: true
    tty: true

  cache:
    image: redis:4.0.10
    ports:
      - "6379:6379"

  es-syncer:
    build: ./es_syncer/
    command: bash -c 'sleep 20 && supervisord -c config/supervisord.conf'
    depends_on:
      - db
      - es
    volumes:
      - ./es_syncer:/es-syncer
    environment:
      PYTHONUNBUFFERED: "0"
      ELASTICSEARCH_URL: 'es'
      ELASTICSEARCH_PORT: "9200"
      DATABASE_HOST: 'db'
      DATABASE_USER: 'deploy'
      DATABASE_PASSWORD: 'deploy'
      DATABASE_NAME: 'openledger'
      DATABASE_PORT: '5432'
      DB_BUFFER_SIZE: '100000'
      COPY_TABLES: 'image'
      SYNCER_POLL_INTERVAL: '60'
    stdin_open: true
    tty: true
