version: '2'

services:
  kafka_monitor:
    image: istresearch/scrapy-cluster:kafka-monitor-1.2.1
    depends_on:
      - kafka
      - redis
    restart: always
    environment:
      LOG_LEVEL: DEBUG
      KAFKA_INCOMING_TOPIC: ccbot.incoming
      KAFKA_GROUP: ccbot-group
  redis_monitor:
    image: istresearch/scrapy-cluster:redis-monitor-1.2.1
    depends_on:
      - kafka
      - redis
      - zookeeper
    restart: always
    environment:
      LOG_LEVEL: DEBUG
      KAFKA_TOPIC_PREFIX: ccbot
  crawler:
    build:
      context: .
      dockerfile: ./docker/crawler/Dockerfile.validator
    depends_on:
      - kafka
      - redis
      - zookeeper
    restart: always
    environment:
      SC_LOG_LEVEL: DEBUG
  rest:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    depends_on:
      - kafka
      - redis
    restart: always
    ports:
      - "5343:5343"
    environment:
      KAFKA_PRODUCER_TOPIC: ccbot.incoming
      KAFKA_TOPIC_PREFIX: ccbot
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
