services:
  catalog_indexer_worker:
    profiles:
      - api
      - catalog_indexer_worker
    build:
      context: ./
      target: indexer_worker
      args: # Automatically inferred from env vars, unless specified
        - INDEXER_WORKER_PY_VERSION
        - PDM_INSTALL_ARGS=--dev
    ports:
      - "50282:8003"
    depends_on:
      - db
      - upstream_db
      - es
    volumes:
      - .:/indexer_worker:z
    env_file:
      - env.docker
      - .env
    stdin_open: true
    tty: true
