name: openverse/load-img
description: Download and import Docker images from artifacts

inputs:
  setup_images:
    default: "upstream_db ingestion_server catalog api api_nginx frontend"
    description: Space-separated list of image names

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Doesn't use `setup-env` because the next step uses `npm`, not `pnpm`.
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: "package.json"

    - name: Install `@actions/artifact`
      shell: bash
      run: |
        npm install @actions/artifact

    - name: Download images
      uses: actions/github-script@v6
      with:
        script: |
          const artifact = require("@actions/artifact")
          const artifactClient = artifact.create()
          const images = "${{ inputs.setup_images }}".split(" ")
          for (image of images) {
            await artifactClient.downloadArtifact(image, "/tmp", { createArtifactFolder: false })
          }

    - name: Load images
      shell: bash
      run: |
        images=(${{ inputs.setup_images }});
        for image in "${images[@]}"; do
          docker load --input /tmp/${image}.tar
        done
