name: openverse/load-img
description: Download and import Docker images from artifacts

inputs:
  setup_images:
    default: '["upstream_db", "ingestion_server", "catalog", "api", "api_nginx"]'
    description: JSON-encoded list of image names

runs:
  using: "composite"
  steps:
    # Upstream DB
    - name: Download image `upstream_db`
      uses: actions/download-artifact@v3
      if: contains(fromJson(inputs.setup_images), 'upstream_db')
      with:
        name: upstream_db
        path: /tmp

    - name: Load image `upstream_db`
      if: contains(fromJson(inputs.setup_images), 'upstream_db')
      shell: bash
      run: |
        docker load --input /tmp/upstream_db.tar

    # Catalog
    - name: Download image `catalog`
      uses: actions/download-artifact@v3
      if: contains(fromJson(inputs.setup_images), 'catalog')
      with:
        name: catalog
        path: /tmp

    - name: Load image `catalog`
      if: contains(fromJson(inputs.setup_images), 'catalog')
      shell: bash
      run: |
        docker load --input /tmp/catalog.tar

    # Ingestion server
    - name: Download image `ingestion_server`
      uses: actions/download-artifact@v3
      if: contains(fromJson(inputs.setup_images), 'ingestion_server')
      with:
        name: ingestion_server
        path: /tmp

    - name: Load image `ingestion_server`
      if: contains(fromJson(inputs.setup_images), 'ingestion_server')
      shell: bash
      run: |
        docker load --input /tmp/ingestion_server.tar

    # API
    - name: Download image `api`
      uses: actions/download-artifact@v3
      if: contains(fromJson(inputs.setup_images), 'api')
      with:
        name: api
        path: /tmp

    - name: Load image `api`
      if: contains(fromJson(inputs.setup_images), 'api')
      shell: bash
      run: |
        docker load --input /tmp/api.tar

    - name: Download image `api_nginx`
      uses: actions/download-artifact@v3
      if: contains(fromJson(inputs.setup_images), 'api_nginx')
      with:
        name: api_nginx
        path: /tmp

    - name: Load image `api_nginx`
      if: contains(fromJson(inputs.setup_images), 'api_nginx')
      shell: bash
      run: |
        docker load --input /tmp/api_nginx.tar
