name: openverse/load-img
description: Download and import Docker images from artifacts

inputs:
  setup_ingestion_server:
    default: "true"
    description: Whether to set up ingestion server image

  setup_api:
    default: "true"
    description: Whether to set up API image

  setup_catalog:
    default: "true"
    description: Whether to set up catalog image

  setup_upstream_db:
    default: "true"
    description: Whether to set up upstream DB image

runs:
  using: "composite"
  steps:
    # Upstream DB
    - name: Download image `upstream_db`
      uses: actions/download-artifact@v3
      if: inputs.setup_upstream_db == 'true'
      with:
        name: upstream_db
        path: /tmp

    - name: Load image `upstream_db`
      if: inputs.setup_upstream_db == 'true'
      shell: bash
      run: |
        docker load --input /tmp/upstream_db.tar

    # Catalog
    - name: Download image `catalog`
      uses: actions/download-artifact@v3
      if: inputs.setup_catalog == 'true'
      with:
        name: catalog
        path: /tmp

    - name: Load image `catalog`
      if: inputs.setup_catalog == 'true'
      shell: bash
      run: |
        docker load --input /tmp/catalog.tar

    # Ingestion server
    - name: Download image `ingestion_server`
      uses: actions/download-artifact@v3
      if: inputs.setup_ingestion_server == 'true'
      with:
        name: ingestion_server
        path: /tmp

    - name: Load image `ingestion_server`
      if: inputs.setup_ingestion_server == 'true'
      shell: bash
      run: |
        docker load --input /tmp/ingestion_server.tar

    # API
    - name: Download image `api`
      uses: actions/download-artifact@v3
      if: inputs.setup_api == 'true'
      with:
        name: api
        path: /tmp

    - name: Load image `api`
      if: inputs.setup_api == 'true'
      shell: bash
      run: |
        docker load --input /tmp/api.tar
