name: cccatalog-frontend-ci

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - develop

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  ci:
    name: Run CI tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.14.1'

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm run unit

    - name: Run build
      run: npm run build
