name: GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CI env
        uses: ./.github/actions/setup-env
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          setup_python: false

      - name: Fetch translation files
        run: just frontend/run i18n

      - name: Build Storybook
        run: just frontend/run storybook:build

      - name: Build Tailwind Config Viewer
        run: just frontend/run tcv:build

      # This makes the TCV available at the `/tailwind` directory in the gh-pages
      - name: Merge TCV and Storybook builds
        run: |
          mv frontend/.tcv-export frontend/storybook-static/tailwind
          mv frontend/storybook-static /tmp/gh-pages

      - name: Checkout repository at `gh-pages` branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Preserve previews
        run: mv _preview /tmp/gh-pages/_preview

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/gh-pages
          force_orphan: true

      - name: Checkout repository # again, to enable cleaning.
        if: always()
        uses: actions/checkout@v3
