name: Automation of Project Board

on:
  issues :
    types : [ opened ]
  pull_request :
    types : [ opened ]
jobs:
  Add Issue And PR:
    runs-on: ubuntu-latest
    steps:
    - name: Automate Issues Add
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/creativecommons/projects/10
    - name: Automate PR Add
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/creativecommons/projects/7
      
