name: Label PR

on:
  repository_dispatch:
    types:
      - label_pr

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  PR_URL: ${{ github.event.client_payload.pr_url }}

jobs:
  label_pr:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: ./python
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user pipenv
          pipenv install --deploy

      - name: Label PR
        working-directory: ./python
        run: |
          pipenv run python label_pr.py \
            --pr-url $PR_URL
