name: Label PR

on:
  repository_dispatch:
    types:
      - label_pr

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Can't use GITHUB_TOKEN to access PRs in other repos
  PR_URL: ${{ github.event.client_payload.pr_url }}
  GH_LOGIN: ${{ secrets.GH_LOGIN }}
  GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
  GH_2FA_SECRET: ${{ secrets.GH_2FA_SECRET }}

jobs:
  label_pr:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI env
        uses: ./.github/actions/setup-env
        with:
          setup_nodejs: false # Node.js is not needed to run Python automations.
          install_recipe: "automations/python/install"

      - name: Label PR
        working-directory: ./automations/python
        run: |
          pipenv run python label_pr.py \
            --pr-url "$PR_URL"
