name: Label sync
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#label-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # at 00:00

env:
  LOGGING_LEVEL: 20 # corresponds to INFO
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  sync_labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI env
        uses: ./.github/actions/setup-env
        with:
          setup_nodejs: false # Node.js is not needed to run Python automations.
          install_recipe: "automations/python/install"

      - name: Sync standard labels
        working-directory: ./automations/python
        run: |
          pipenv run python sync_labels.py
