name: linting-and-formatting

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Setup flake8 annotations  # To annotate the errors in the pull request
      uses: rbialon/flake8-annotations@v1
    - name: Lint
      # Lint only for changed files, rather than the entire repository
      run: |
        pip install pre-commit
        pre-commit run --all-files
