name: Project automation

on:
  workflow_dispatch:
  schedule:
  - cron: "*/15 * * * *" # every 15 minutes

env:
  LOGGING_LEVEL: 20 # corresponds to INFO
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  add_issues:
    name: Add new issues
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install --user pipenv
        pipenv install --deploy

    - name: Add issues to "Backlog"
      working-directory: ./python
      run: |
        pipenv run python new_issues_and_prs.py \
        --entity-type "issue" \
        --project-number 3 \
        --target-column "Backlog" \
        --period 30

  add_prs:
    name: Add new PRs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install --user pipenv
        pipenv install --deploy

    - name: Add PRs to "Needs review"
      working-directory: ./python
      run: |
        pipenv run python new_issues_and_prs.py \
        --entity-type "pr" \
        --project-number 3 \
        --target-column "Needs review" \
        --period 30

  move_issues:
    name: Move issues to "In Progress"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install --user pipenv
        pipenv install --deploy

    - name: Move issues from "To do"
      working-directory: ./python
      run: |
        pipenv run python issues_with_prs.py \
        --project-number 3 \
        --source-column "To do" \
        --target-column "In progress"

    - name: Move issues from "Backlog"
      working-directory: ./python
      run: |
        pipenv run python issues_with_prs.py \
        --project-number 3 \
        --source-column "Backlog" \
        --target-column "In progress"
