name: Project Thread Update Reminders

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    # Prevent running this workflow on forks, it's unnecessary for external contributors
    if: github.repository_owner == 'WordPress'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const script = require('./automations/js/src/project_thread_updates.js')
            await script({github, core})
